# Generated by Django 5.1.6 on 2025-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="answers",
            field=models.JSONField(default=list),
        ),
    ]
