# Generated by Django 5.1.6 on 2025-02-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="state",
        ),
    ]
