# Generated by Django 5.1.6 on 2025-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_game_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="name",
        ),
        migrations.AddField(
            model_name="game",
            name="start_category",
            field=models.CharField(default="", max_length=200),
        ),
    ]
