# Generated by Django 5.1.6 on 2025-02-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_game_name_game_start_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="starting_word",
            field=models.CharField(default="", max_length=200),
        ),
    ]
