# Generated by Django 5.1.6 on 2025-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_game_starting_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="starting_word",
            field=models.CharField(default="test", max_length=200),
        ),
    ]
