# Generated by Django 5.1.6 on 2025-02-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_game_starting_word"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="starting_word",
        ),
    ]
