# Generated by Django 5.1.6 on 2025-02-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_remove_game_starting_word"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="start_category",
            new_name="category",
        ),
    ]
